import globals from "globals";
import pluginJs from "@eslint/js";

/** @type {import('eslint').Linter.Config[]} */
export default [
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        checkForMiddleClick: "readonly",
        delayedStartupPromise: "readonly",
        gBrowser: "readonly",
        gCustomizeMode: "readonly",
        gContextMenu: "readonly",
        gIdentityHandler: "readonly",
        gNavToolbox: "readonly",
        gPermissionPanel: "readonly",
        gProtectionsHandler: "readonly",
        gSync: "readonly",
        gTabsPanel: "readonly",
        gUnifiedExtensions: "readonly",
        gURLBar: "readonly",
        openTrustedLinkIn: "readonly",
        AboutReaderParent: "readonly",
        BookmarkingUI: "readonly",
        BookmarksEventHandler: "readonly",
        BrowserCommands: "readonly",
        BrowserPageActions: "readonly",
        Cc: "readonly",
        Ci: "readonly",
        Components: "readonly",
        ContentAnalysis: "readonly",
        ContextualIdentityService: "readonly",
        CustomizableUI: "readonly",
        ChromeUtils: "readonly",
        DownloadsIndicatorView: "readonly",
        Favicons: "readonly",
        FullPageTranslationsPanel: "readonly",
        FullZoom: "readonly",
        FirefoxViewHandler: "readonly",
        MigrationUtils: "readonly",
        NetUtil: "readonly",
        PageActions: "readonly",
        PageProxyClickHandler: "readonly",
        PanelUI: "readonly",
        PictureInPicture: "readonly",
        PlacesCommandHook: "readonly",
        PlacesMenu: "readonly",
        PlacesToolbarHelper: "readonly",
        PlacesUtils: "readonly",
        Services: "readonly",
        SidebarController: "readonly",
        ShoppingSidebarParent: "readonly",
        UC_API: "readonly",
        ZoomManager: "readonly",
      },
    },
  },
  pluginJs.configs.recommended,
];
